### ISSUE TITLE
enum values being sent as strings

### ISSUE THREAD

**Issue by Faen668** [AtilioA/BG3-MCM#20]
when subscribing to the 'MCM_Setting_Saved' event, enum values seem to come through as strings rather than numeric values.

I may have missed something but if this is the case then translations would be a nightmare as you have to hardcode the strings for comparison rather than just the enum value of the choice.

**Comment by AtilioA** [comment]
Enums have string values. Could you clarify how this would affect translation handling?

**Comment by Faen668** [comment]
No I can't clarify it because I'm totally wrong and you should forget you ever saw this :)

I got confused as I had my .loca text the same as the blueprint so it appeared to just be passing the localised text not the blueprint defined value.

Apologies!
